### ISSUE TITLE
Massive Amounts of Request

### ISSUE THREAD

**Issue by ssbtoday** [alexcican/tiii.me#10]
Perhaps adding a delay before the search begins or having a search button instead of querying the server as soon as a character is added? Unless you've got a massive datacenter at your disposal, I don't think it's that good of an idea.

**Comment by alexcican** [comment]
Nowadays it’s not getting that much traffic. But when it did, I had a delay of 3s: https://github.com/alexcican/tiii.me/commit/913c312f495d724b5b4e1722f42eb7a34e3c5f95
