### ISSUE TITLE
Show name is not autocompleted when I move to the next field

### ISSUE THREAD

**Issue by pangolingo** [alexcican/tiii.me#12]
I type in "breaking bad", then press tab to get to the number field.

Result: nothing at all is displayed
Expected result: the Breaking Bad show will be selected

If the user doesn't select one of the autosuggested shows, the first autosuggested show should be selected when the field loses focus.

**Comment by alexcican** [comment]
@pangolingo I don’t know what tab you pressed or on which browser, but the show is autoselected on tab or enter… Works on Chrome, Safari, etc.

**Comment by pangolingo** [comment]
It looks like the only occurs when the app is still searching. If it has already found search results, it does autoselect correctly. It takes approximately 2 seconds to return search results.

**Comment by alexcican** [comment]
@pangolingo this is because I got over 250K unique users only today… the servers must be burning!

**Comment by pangolingo** [comment]
The problems that come with success are the best kind of problems to have :smile: 
If query times are a big concern, you could cache the top 100 or 1000 results in a static text file (along with the show data) and check that before you query the API. You'd only need to update the file every few months.

**Comment by alexcican** [comment]
@pangolingo Technology used is HTML and JS only. Hosting on GitHub. If I was on Heroku, AWS, etc., that would be the wise thing to do, yes. Also, that text file would get huge (different entries for 1 show depending on # of seasons).
