### ISSUE TITLE
Responsive? 

### ISSUE THREAD

**Issue by kevinkhill** [alexcican/tiii.me#13]
I tried to visit your page on my phone, but every thing was overlapping and the font was too big.

Chrome on a LG G3

**Comment by kevinkhill** [comment]
![Imgur](http://i.imgur.com/JMWfU9K.jpg)

**Comment by alexcican** [comment]
@kevinkhill you are correct. I’m doing a poor job at responsiveness. That was because I was thinking of making a mobile app for it.
