### ISSUE TITLE
Problem with Sherlock Holmes

### ISSUE THREAD

**Issue by tacticurv** [alexcican/tiii.me#15]
When you enter sherlock holmes either the image doesn't appear or the Time crashes. I am using Google Chrome Browser on Desktop.

Seems like the problem is with Trakt images not being able to show up. When I tried to access the image http://image.tmdb.org/t/p/w342/624zSip1AETVlHSeisv6GOutxdV.jpg it shows up Error 1001

**Comment by kandebonfim** [comment]
hmmm, everything seems working now, @tacticurv. How about close it, @alexcican?
