### ISSUE TITLE
Many shows error due to runtime policy change

### ISSUE THREAD

**Issue by adebrecht661** [alexcican/tiii.me#17]
No idea if you still intend to maintain this, but it seems that sometime recently TMDb has added per-episode runtimes and changed their policy to prefer leaving the series-level runtime blank if per-episode runtimes aren't consistent. This appears to break the way you currently use the API response for quite a few shows. Looks like their API docs are down, so I can't tell how much work it would be to loop through the runtime of all episodes to get an average.

**Comment by alexcican** [comment]
[fixed](https://github.com/alexcican/tiii.me/commit/625f02e12a396d6a1a5f2597007b14a7b819e8ea)!
