### ISSUE TITLE
Chrome Doesn't Display Time

### ISSUE THREAD

**Issue by ryananthonydrake** [alexcican/tiii.me#2]
Hi there, when I search for a show (used two examples: Gossip Girl and The Simpsons), I entered it correctly, the time flashed for a brief 0.5 secs before just leaving me to stare at the DVD Box Cover?

Any reason why that is?

**Comment by alexcican** [comment]
Weird… seems to be working fine for me. What version of Chrome and OS are you using? Also, try to reset all data and try again, it might have been an API connection issue (go to site’s menu-top-right, and at the bottom click “reset all data”)

**Comment by ryananthonydrake** [comment]
Working now!
