### ISSUE TITLE
Can't find The Office?

### ISSUE THREAD

**Issue by AriX** [alexcican/tiii.me#3]
I can't get the TV show "The Office" to show up. Trakt has it as "The Office (US)" but this doesn't work either. ("The Office 1995" is not the right show)

**Comment by alexcican** [comment]
search for “the office u”. Currently, I’m limiting the amount of results returned to 1, because the servers of the APIs I’m using can’t handle the traffic. So the autosuggestion is not very useful…

**Comment by AriX** [comment]
Ahh, got it :)
