### ISSUE TITLE
Duplicates should be ignored

### ISSUE THREAD

**Issue by 1ace** [alexcican/tiii.me#7]
When you add a series a second time, its time is added again.
I think it should check when you add the series, or even better: disable the entry in the suggestions.

**Comment by alexcican** [comment]
I had it like that (see commented out: https://github.com/alexcican/tiii.me/blob/gh-pages/scripts/partials/_tv-show.js#L98 ) and many asked for the functionality to add same show multiple times.

**Comment by 1ace** [comment]
OK, I didn't know that.
