### ISSUE TITLE
Calculate time spent for a list of TV Shows watched?

### ISSUE THREAD

**Issue by sitz** [alexcican/tiii.me#8]
Hi there,

I just found out about http://tiii.me. The number looks interesting to find out but, when you've seen a bunch of TV Shows it's really painful to add every one of them manually here!
I generally keep track of all the TV Shows watched on Facebook. I suppose most people do on some sort of website.
How about giving a option for user to fetch the watched shows list and calculate the total time used (wasted!) there?

Let me know if you would like to include this as a feature into your main application.
I can look into it and send you a pull request in some time.

**Comment by alexcican** [comment]
@SITZ Hey, that would be nice. However, I think it might take some time to do that? I don’t have good knowledge of Facebook’s API. If you want to contribute to this feature, feel free to do so, and I’ll mention you :)
